language: rust
rust:
  - nightly
env:
  - LoadingType=Disk RUST_BACKTRACE=full RUST_LOG=search_lib=trace
  - LoadingType=InMemory RUST_BACKTRACE=full RUST_LOG=search_lib=trace
  - LoadingType=InMemoryUnCompressed RUST_BACKTRACE=full RUST_LOG=search_lib=trace