[package]
name = "native_search"
version = "0.1.0"
authors = ["Pascal Powerman <you@gmail.com>"]
autobenches = false

[dependencies]
json_converter = {path = "json_converter"}
serde_derive = "1.0.1"
serde = "1.0.1"
serde_json = "1.0.0"
levenshtein_automata = { git = "https://github.com/PSeitz/levenshtein-automata", features = ["fst_automaton"] }
fxhash = { git = "https://github.com/cbreeden/fxhash" }
regex = "0.2"
lazy_static = "0.2.2"
fnv = "1.0.3"
fst = "0.3"
log = "0.4"
env_logger = "0.3"
vint = { git = "https://github.com/PSeitz/rust_vint"}
num = "0.1"
heapsize = "0.4.1"
heapsize_derive = "0.1.4"
snap = "0.2"
byteorder = "1.2.1"
bincode = "1.0.0"
measure_time = "0.1"
chrono = "0.4"
flexi_logger = "0.6.11"
rayon = "1.0.1"
itertools = "0.7.3"
ordered-float = "0.5.0"
chashmap = "2.2.0"
parking_lot = {version = "0.5", features = ["nightly"]}
lru_time_cache = "0.8.0"
memmap = "0.6.2"
half = {version = "1.1.0", features = ["use-intrinsics", "serialize", "std"]}
flame = { version = "0.2.0", optional = true }
flamer = { version = "0.2.0", optional = true }
crossbeam-channel = "0.1.2"
crossbeam-utils = "0.2.1"
mayda = {git = "https://github.com/PSeitz/mayda"}
prettytable-rs = "^0.6"
colored = "1.4"
flate2 = "1.0"

rocket = "0.3"
rocket_contrib = "0.3"
rocket_codegen = "0.3"

# time = "0.1"
# csv = "0.15.0"
# lz4 = "1.22.0"
# hyper = "0.10.9"
# bit-set = "0.4.0"
# bit-vec = "0.4.4"
# sled = "0.15.14"
# lru-cache = "0.1.1"
# utf8-ranges = "1.0.0"
# fixedbitset = "0.1.8"
# fst-levenshtein = "0.2.0"

[features]
default = []
flame_it = ["flame", "flamer"]

# [dependencies.bodyparser]
# version = "0.7.0"

# [dependencies.urlencoded]
# version = "0.5.0"

[dev-dependencies]
env_logger = "0.3"
pretty_assertions = "0.1.2"
stainless = {git = "https://github.com/PSeitz/stainless"}
criterion = "0.2.3"
tempfile = "3"
rand = "0.4"

[lib]
name = "search_lib"
path = "src/lib.rs"

[[bench]]
name = "bench_jmdict"
path = "benches/bench_jmdict.rs"
harness = false

[[bench]]
name = "bench_collection"
path = "benches/bench_collection.rs"
[[bench]]
name = "bench_persistence"
path = "benches/bench_persistence.rs"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = 'unwind'
