[package]
authors = ["Pascal Powerman <you@gmail.com>"]
autobenches = false
name = "native_search"
version = "0.1.0"
[[bench]]
harness = false
name = "bench_jmdict"
path = "benches/bench_jmdict.rs"

[[bench]]
name = "bench_collection"
path = "benches/bench_collection.rs"

[[bench]]
name = "bench_persistence"
path = "benches/bench_persistence.rs"

[dependencies]
bincode = "1.0.0"
byteorder = "1.2.1"
chashmap = "2.2.0"
chrono = "0.4"
colored = "1.4"
cpuprofiler = "0.0.3"
crossbeam = "0.3.2"
crossbeam-channel = "0.1.2"
crossbeam-utils = "0.2.1"
dump = "0.1"
env_logger = "0.3"
fixedbitset = "0.1.9"
flate2 = "1.0"
flexi_logger = "0.6"
fnv = "1.0.3"
fst = "0.3"
heapsize = "0.4.1"
heapsize_derive = "0.1.4"
itertools = "0.7.3"
lazy_static = "1.0.0"
log = "0.4"
lru-cache = "0.1.1"
lru_time_cache = "0.8.0"
measure_time = "0.6.0"
memmap = "0.6.2"
num = "0.1"
prettytable-rs = "^0.6"
rayon = "1.0.2"
regex = "0.2"
serde = "1.0.1"
serde_derive = "1.0.1"
serde_json = "1.0.0"

[dependencies.btree]
git = "https://github.com/wspeirs/btree"

[dependencies.buffered_index_writer]
path = "buffered_index_writer"

[dependencies.flame]
optional = true
version = "0.2.0"

[dependencies.flamer]
optional = true
version = "0.2.0"

[dependencies.half]
features = ["use-intrinsics", "serialize", "std"]
version = "1.1.0"

[dependencies.json_converter]
path = "json_converter"

[dependencies.levenshtein_automata]
features = ["fst_automaton"]
git = "https://github.com/PSeitz/levenshtein-automata"

[dependencies.ordered-float]
features = ["serde"]
version = "0.5.0"

[dependencies.parking_lot]
features = ["nightly"]
version = "0.5"

[dependencies.term_hashmap]
git = "https://github.com/PSeitz/rust_string_hashmap"

[dependencies.uuid]
features = ["v4"]
version = "0.6"

[dependencies.vint]
git = "https://github.com/PSeitz/rust_vint"

[dev-dependencies]
criterion = "0.2.3"
env_logger = "0.3"
pretty_assertions = "0.1.2"
rand = "0.4"
tempfile = "3"

[dev-dependencies.stainless]
git = "https://github.com/PSeitz/stainless"

[features]
default = []
enable_cpuprofiler = []
flame_it = ["flame", "flamer"]

[lib]
name = "search_lib"
path = "src/lib.rs"
[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
panic = "unwind"
