[package]
name = "native_search"
version = "0.1.0"
authors = ["Pascal Powerman <you@gmail.com>"]

[dependencies]
serde_derive = "1.0.1"
serde = "1.0.1"
serde_json = "1.0.0"
rand = "0.4"
# tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }
levenshtein_automaton = { git = "https://github.com/tantivy-search/levenshtein-automata" }
regex = "0.2"
lazy_static = "0.2.2"
fnv = "1.0.3"
bit-set = "0.4.0"
bit-vec = "0.4.2"
fst = "0.3"
# fst = { git = "https://github.com/PSeitz/fst"}
fst-levenshtein = "0.2.0"
log = "0.4"
env_logger = "0.3"
csv = "0.15.0"
time = "0.1"
trie = { git = "https://github.com/contain-rs/trie"}
hyper = "0.10.9"
num = "0.1"
heapsize = "0.4.1"
heapsize_derive = "0.1.4"
snap = "0.2"
byteorder = "1.0.0"
bincode = "0.8.0"
measure_time = "0.1"
chrono = "0.4"
sled = "0.14.1"
flexi_logger = "0.6.11"
json_converter = {path = "json_converter"}
rayon = "0.9"
itertools = "0.7.3"
ordered-float = "0.5.0"
chashmap = "2.2.0"
parking_lot = {version = "0.5", features = ["nightly"]}
lru-cache = "0.1.1"

flame = "0.2.0"
flamer = { git = "https://github.com/llogiq/flamer"}
crossbeam-channel = "0.1.2"
crossbeam-utils = "0.2.1"
mayda = {git = "https://github.com/PSeitz/mayda"}
prettytable-rs = "^0.6"
utf8-ranges = "1.0.0"
colored = "1.4"

iron = "0.5.1"
iron-cors = "0.6.0-rc.1"
iron_compress = "0.1.3"
multipart = "=0.13.3"
router = "0.5.1"

[dependencies.bodyparser]
version = "0.7.0"

[dependencies.urlencoded]
version = "0.5.0"

[dev-dependencies]
env_logger = "0.3"
pretty_assertions = "0.1.2"
stainless = "*"
criterion = "0.1.1"

[lib]
name = "search_lib"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "create_index"
path = "src/create_index.rs"

[[bench]]
name = "bench_jmdict"
path = "benches/bench_jmdict.rs"
harness = false

[[bench]]
name = "bench_collection"
path = "benches/bench_collection.rs"
