[package]
authors = ["Pascal Seitz <pascal.seitz@gmail.com>"]
autobenches = false
name = "veloci"
version = "0.1.0"
edition = "2018"

[[bench]]
harness = false
name = "bench_jmdict"
path = "benches/bench_jmdict.rs"

[[bench]]
name = "bench_collection"
path = "benches/bench_collection.rs"

[[bench]]
name = "bench_persistence"
path = "benches/bench_persistence.rs"

[dependencies]
byteorder = "1.2.6"
chrono = "0.4.6"
clap = "2.32.0"
colored = "1.6.1"
cpuprofiler = "0.0.3"
crossbeam-channel = "0.2.6"
dump = "0.1.1"
fixedbitset = "0.1.9"
flexi_logger = "0.9.2"
fnv = "1.0.6"
fst = "0.3.2"
heapsize = "0.4.2"
heapsize_derive = "0.1.4"
itertools = "0.7.8"
lazy_static = "1.1.0"
log = "0.4.5"
lru-cache = "0.1.1"
lru_time_cache = "0.8.0"
measure_time = "0.6.0"
memmap = "0.7.0"
num = "0.2.0"
prettytable-rs = "0.8.0"
rayon = "1.0.2"
regex = "1.0.5"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.32"
failure = "0.1.2"

[dependencies.buffered_index_writer]
path = "buffered_index_writer"

[dependencies.doc_store]
path = "doc_store"

[dependencies.flame]
optional = true
version = "0.2.2"

[dependencies.flamer]
optional = true
version = "0.2.5"

[dependencies.half]
features = ["use-intrinsics", "serialize", "std"]
version = "1.3.0"

[dependencies.json_converter]
path = "json_converter"

[dependencies.levenshtein_automata]
features = ["fst_automaton"]
git = "https://github.com/PSeitz/levenshtein-automata"

[dependencies.ordered-float]
features = ["serde"]
version = "1.0.1"

[dependencies.parking_lot]
features = ["nightly"]
version = "0.6.4"

[dependencies.parser]
path = "parser"

[dependencies.term_hashmap]
git = "https://github.com/PSeitz/rust_string_hashmap"

[dependencies.vint]
git = "https://github.com/PSeitz/rust_vint"

[dev-dependencies]
pretty_assertions = "0.5.1"
rand = "0.5.5"
tempfile = "3.0.4"

[dev-dependencies.criterion]
features = []
version = "0.2.5"

[features]
default = []
enable_cpuprofiler = []
flame_it = ["flame", "flamer"]

[lib]
name = "search_lib"
path = "src/lib.rs"
[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
panic = "unwind"
