[package]
name = "native_search"
version = "0.1.0"
authors = ["Pascal Powerman <you@gmail.com>"]

[dependencies]
rustc-serialize = "0.3.22"
serde_derive = "0.9"
serde = "0.9.7"
serde_json = "0.9"
rand = "0.3"
futures = "0.1.9"
futures-cpupool = "0.1"
tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }
regex = "0.2"
lazy_static = "0.2.2"
fnv = "1.0.3"
bit-set = "0.4.0"
fst = "0.1"
log = "0.3"
env_logger = "0.3"
flate2 = "0.2"

[dev-dependencies]
env_logger = "0.3"