[package]
name = "native_search"
version = "0.1.0"
authors = ["Pascal Powerman <you@gmail.com>"]

[dependencies]
rustc-serialize = "0.3.22"
serde = "0.9.7"
serde_json = "0.9"
rand = "0.3"
futures = "0.1.9"
futures-cpupool = "0.1"
tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }