[package]
name = "native_search"
version = "0.1.0"
authors = ["Pascal Powerman <you@gmail.com>"]

[dependencies]
serde_derive = "1.0.1"
serde = "1.0.1"
serde_json = "1.0.0"
rand = "0.3"
# tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }
regex = "0.2"
lazy_static = "0.2.2"
fnv = "1.0.3"
bit-set = "0.4.0"
bit-vec = "0.4.2"
fst = "0.1"
log = "0.3"
env_logger = "0.3"
# abomonation = "0.4.5"
csv = "0.15.0"
iron = "0.5.1"
time = "0.1"
router = "*"
hyper = "0.10.9"
num = "0.1"
heapsize = "0.3.9"
snap = "0.2"
byteorder = "1.0.0"
bincode = "0.8.0"
measure_time = "0.1"

[dependencies.bodyparser]
git = "https://github.com/iron/body-parser.git"

[dev-dependencies]
env_logger = "0.3"
colored = "1.4"
pretty_assertions = "0.1.2"

[lib]
name = "native_search"
path = "src/lib.rs"

[[bin]]
name = "myapp"
path = "src/main.rs"
