closure_block_indent_threshold = 0
struct_lit_width = 70
struct_variant_width = 70
array_horizontal_layout_threshold = 15
indent_style = "Visual"
control_brace_style = "AlwaysSameLine"
chain_width = 100
chain_split_single_child = true
max_width = 155
fn_call_width = 155
error_on_line_overflow_comments = false
fn_args_density = "Compressed"
single_line_if_else_max_width = 100
struct_field_align_threshold = 20
use_try_shorthand = true
