[package]
name = "json_converter"
version = "0.1.0"
authors = ["Pascal Seitz <pascal.seitz@gmail.com>"]

[dependencies]
serde_derive = "1.0.1"
serde = "1.0.1"
serde_json = "1.0.0"
rand = "0.3"
regex = "0.2"
lazy_static = "0.2.2"
fnv = "1.0.3"
log = "0.4"
heapsize = "0.3.9"
flexi_logger = "0.6"
rayon = "0.9"
chashmap = { git = "https://github.com/nathanaeljones/tfs"}

[dev-dependencies]
colored = "1.4"
pretty_assertions = "0.1.2"
stainless = {git = "https://github.com/PSeitz/stainless"}
criterion = "0.2.3"

[[bench]]
name = "bench"
harness = false