[package]
authors = ["Pascal Seitz <pascal.seitz@gmail.com>"]
build = "build.rs"
name = "parser"
version = "0.1.0"
[build-dependencies]
lalrpop = "0.15.0"

[dependencies]
lalrpop-util = "0.16.0"
nom = "4.0.0"
regex = "0.2.0"
