[package]
authors = ["Pascal Seitz <pascal.seitz@gmail.com>"]
edition = "2018"
name = "doc_store"
version = "0.1.0"
[dependencies]
lz4 = "1.23.1"
vint32 = { version = "0.2.0", features= ["common-encoding"]}
